// Code generated by protoc-gen-go.
// source: defs.proto
// DO NOT EDIT!

/*
Package odf is a generated protocol buffer package.

It is generated from these files:
	defs.proto

It has these top-level messages:
	NIB
	Revision
*/
package odf

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type NIB struct {
	UUID             *string     `protobuf:"bytes,1,req" json:"UUID,omitempty"`
	Revisions        []*Revision `protobuf:"bytes,2,rep" json:"Revisions,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *NIB) Reset()         { *m = NIB{} }
func (m *NIB) String() string { return proto.CompactTextString(m) }
func (*NIB) ProtoMessage()    {}

func (m *NIB) GetUUID() string {
	if m != nil && m.UUID != nil {
		return *m.UUID
	}
	return ""
}

func (m *NIB) GetRevisions() []*Revision {
	if m != nil {
		return m.Revisions
	}
	return nil
}

type Revision struct {
	MetadataID       *string  `protobuf:"bytes,1,req" json:"MetadataID,omitempty"`
	ContentIDs       []string `protobuf:"bytes,2,rep" json:"ContentIDs,omitempty"`
	UTCTimestamp     *int64   `protobuf:"varint,3,opt" json:"UTCTimestamp,omitempty"`
	DeviceID         *string  `protobuf:"bytes,4,opt" json:"DeviceID,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Revision) Reset()         { *m = Revision{} }
func (m *Revision) String() string { return proto.CompactTextString(m) }
func (*Revision) ProtoMessage()    {}

func (m *Revision) GetMetadataID() string {
	if m != nil && m.MetadataID != nil {
		return *m.MetadataID
	}
	return ""
}

func (m *Revision) GetContentIDs() []string {
	if m != nil {
		return m.ContentIDs
	}
	return nil
}

func (m *Revision) GetUTCTimestamp() int64 {
	if m != nil && m.UTCTimestamp != nil {
		return *m.UTCTimestamp
	}
	return 0
}

func (m *Revision) GetDeviceID() string {
	if m != nil && m.DeviceID != nil {
		return *m.DeviceID
	}
	return ""
}

func init() {
}
